---
### --- GETTING OTHERS HOSTS FACTS --- ###
# It seems that vars using facts like .fqdn in the
# HAPROXY config file cannot be used
# if the .fqdn's hosts isn't in use in the playbook
# We retrived backend's fact in order to ansible to use the
# backends.vars in haproxy.cfg
# Those tasks might be reused in other playbooks to avoid configuration issues


### --- GETTING BACKENDS FACTS --- ###
- name: Display facts
  hosts: backend_*
  gather_facts: true
  tasks:
    - name: get fqdn from ansible
      ansible.builtin.debug:
        var: ansible_fqdn

### --- HAPROXY on FRONT --- ###

# 	Install HAPROXY
- name: Install haproxy on front
  hosts: front_*
  tasks:
#	apt install haproxy
    - name: Install HAPROXY
      apt:
        name: haproxy
        state: latest
#	 STOP HAPROXY Service
    - name: Stop service HAPROXY
      ansible.builtin.service:
        name: haproxy
        state: stopped
#	 Copy HAPROXY config file
    - name: Configurer HAProxy
      template:
        src: "../templates/haproxy/haproxy.cfg"
        dest: "/etc/haproxy/haproxy.cfg"
#	 Restart HAPROXY Service
    - name: restart HAPROXY service
      service:
        name: haproxy
        state: restarted
