---
### --- Install IPTABLES EVERYWHERE --- ###
- name: Installer iptables sur le front
  hosts: front_*
  tasks:
    - name: Install iptables front
      apt:
        name: iptables-persistent
        state: latest
- name: Installer iptables sur les backends
  hosts: backend_*
  tasks:
    - name: Install iptables backends
      apt:
        name: iptables-persistent
        state: latest

### ---  Shared FW config --- ###
#   Allow shared config by all servers
#  Allow SSH, ping,related and subnet
#  UP to the fw sequence
- name: Shared fw config
  hosts: all
  vars:
#    hosts subnet variable
    subnet: "192.168.7.0/24"
  tasks:
# FLUSH INTPUT AND OUTPUT BEFORE STARTING	
    - name: Flush iptables input
      command: iptables -F INPUT
    - name: Flush iptables output
      command: iptables -F OUTPUT
      
    - name: Allow ssh from everywhere
      command: iptables -I INPUT -p tcp --dport 22 -j ACCEPT
    - name: Allow ssh to everywhere
      command: iptables -I OUTPUT -p tcp --dport 22 -j ACCEPT
#	Allow already connected tcp and related to an older connection
    - name: Allow from everywhere related, established
      command: iptables -I INPUT -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
    - name: Allow to everywhere related,established
      command: iptables -I OUTPUT -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
      
    - name: Allow ICMP from everywhere
      command: iptables -A INPUT -p icmp -j ACCEPT
    - name: Allow ICMP to everywhere
      command: iptables -A OUTPUT  -p icmp -j ACCEPT
      
#    Allow anything coming from subnet
    - name: Coming everything from subnet
      command: iptables -A INPUT -s {{subnet}} -j ACCEPT
#     Allow everything going to subnet
    - name: Outgoing everything to subnet
      command: iptables -A OUTPUT -d {{subnet}} -j ACCEPT
#    Allow anything coming from subnet interface
    - name: Coming everything from rfc1918 ens4
      command: iptables -A INPUT -i ens4 -j ACCEPT



### --- IP TABLES on FRONT --- ###
#  Opening port 80,81,82,8500,8080 from internet
#  Respectively : NGINX public IP, NGINX private IP,Wordpress, Ifconfig.io & monitoring
# append at the end of fw sequence
- name: Frontend firewalling INPUT
  hosts: front_*
  tasks:
    - name: Coming tcp:53  DNS
      command: iptables -A INPUT -p tcp --dport 53 -j ACCEPT
    - name: Coming tcp:80 - nginx
      command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    - name: Coming tcp:81 - nginx
      command: iptables -A INPUT -p tcp --dport 81 -j ACCEPT
    - name: Coming tcp:82 - wordpress
      command: iptables -A INPUT -p tcp --dport 82 -j ACCEPT
    - name: Coming tcp:8080 - monitoring
      command: iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
    - name: Coming tcp:8500 - ifconfigio
      command: iptables -A INPUT -p tcp --dport 8500 -j ACCEPT

#     Blackhole everything else
    - name: Coming all is left drop
      command: iptables -A INPUT -j DROP

- name: Frontend firewalling OUTPUT
  hosts: front_*
  vars:
    subnet: "192.168.7.0/24"
  tasks:
#  Opening port 80,81,82,8500,8080 to internet
#  Respectively : NGINX public IP, NGINX private IP,Wordpress, Ifconfig.io & monitoring
# append at the end of fw sequence
    - name: Outgoing everything
      command: iptables -A OUTPUT -j ACCEPT

### --- IP TABLES on  BACKEND --- ###
- name: Backends firewalling INPUT
  hosts: backend_*
  vars:
#    hosts subnet variable
    subnet: "192.168.7.0/24"
#    front public IP
    front_ip: "{% for front in groups.front_gra -%}{{hostvars[front].ansible_facts.default_ipv4.address}}{% endfor -%}"
  tasks:
#  Opening port 80,81,82,8500,8080 from front public IP
#  Respectively : NGINX public IP, NGINX private IP,Wordpress, Ifconfig.io 
# append at the end of fw sequence

#    Allow anything coming on subnet interface
    - name: Coming everything to int ens4
      command: iptables -A INPUT -i ens4 -j ACCEPT
    - name: Coming from front public ip
      command: iptables -A INPUT -p tcp -s {{front_ip}} -j ACCEPT

#     Blackhole everything else
    - name: Coming alls left drop
      command: iptables -A INPUT -j DROP

- name: Backend firewalling OUTPUT
  hosts: backend_*
  vars:
#    hosts subnet variable
    subnet: "192.168.7.0/24"
#    front public IP
    front_ip: "{% for front in groups.front_gra -%}{{hostvars[front].ansible_facts.default_ipv4.address}}{% endfor -%}"
  tasks:
#    Allow everything to go to subnet or front public IP
    - name: Outgoing to subnet
      command: iptables -A OUTPUT -d {{subnet}} -j ACCEPT
    - name: Outgoing to front public ip
      command: iptables -A OUTPUT -d {{front_ip}} -j ACCEPT
    - name: Coming everything to int ens4
      command: iptables -A INPUT -i ens4 -j ACCEPT
