---
### --- GETTING OTHERS HOSTS FACTS --- ###
# It seems that vars using facts like .fqdn in the HAPROXY config file cannot be used
# if the .fqdn's hosts isn't in use in the playbook
# We retrived backend's fact in order to ansible to use the backends.vars in haproxy.cfg
# Those tasks might be reused in other playbooks to avoid configuration issues
- name: Display facts
  hosts: front_*
  gather_facts: true
  tasks:
    - name: get fqdn from ansible
      ansible.builtin.debug:
        var: ansible_fqdn

### ---- INSTALL and CONFIG NGINX on backends ---- ###
# to split backend's regions : 
# simply replace "*" by "gra" and uncomment the last task sequence

- name: Install and configure NGINX on backends
  hosts: backend_*
  vars:
#	Some variables that will be copied to NGINX config file
    helloworld: Coucou
    eductive: "07"
  tasks:
#	Install NGINX
    - name: Ensure package nginx is installed
      apt:
        name: nginx
        state: latest
#	Make sure NGINX is running
    - name: Ensure service nginx is running
      service:
        name: nginx
        state: started
#	Copy config file to NGINX path
    - name: Configure Kitten Page
      template:
        src: "../templates/nginx/index.j2"
        dest: /var/www/html/index.html

### ---- NGINX ON BACKEND SBG ---- ###
#- name: Install and configure NGINX on backend_sbg
#  hosts: backend_sbg
#  vars:
#    helloworld: Coucou
#  tasks:
#    - name: boycott la verification ssh SBG
#      set_fact:
#        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
#    - name: Ensure package nginx is installed
#      apt:
#        name: nginx
#        state: latest
#    - name: Ensure service nginx is running
#      service:
#        name: nginx
#        state: started
#    - name: Configure Kitten Page
#      template:
#        src: ~/PROJET/ansible/nginx/index.j2
#        dest: /var/www/html/index.html
