---
### ---- DOCKER ON BACKEND - RUNNING CONTAINER Everywhere ---- ###

### --- GETTING OTHERS HOSTS FACTS --- ###
# It seems that vars using facts like .fqdn in the HAPROXY config file cannot be used
# if the .fqdn's hosts isn't in use in the playbook
# We retrived backend's fact in order to ansible to use the backends.vars in haproxy.cfg
# Those tasks might be reused in other playbooks to avoid configuration issues
- name: Display facts
  hosts: front_*
  gather_facts: true
  tasks:
    - name: get fqdn from ansible
      ansible.builtin.debug:
        var: ansible_fqdn

- name: RUNNING DOCKER WORDPRESS
  # Docker playbook should have run and
  # installed packages and made /build directory
  hosts: backend_*
  vars:
#	Variables used to locate config files and dir folder
    defaut_file_repo: "../templates/wordpress/docker-compose.yml"
    defaut_app_name: wordpress
    defaut_wordpress_folder: /build/{{ defaut_app_name }}
  tasks:
#	Create /build folder that will contain app
    - name: Create a directory /build
      ansible.builtin.file:
        path: /build
        state: directory
        mode: '0755'
#	Create /build/app_name
    - name: Create a directory with app name
      ansible.builtin.file:
        path: "{{ defaut_wordpress_folder }}"
        state: directory
        mode: '0755'
#	Copy docker-compose file used to build container
    - name: Copy wordpress docker-compose file
      template:
        src: "{{ defaut_file_repo }}"
        dest: "{{ defaut_wordpress_folder }}"
#	Start command 'docker-compose up' based on behind file location
    - name: Start docker compose UP
      docker_compose:
        project_src: "{{  defaut_wordpress_folder  }}"
        state: present
